imagePullSecrets: []

node:
  # https://github.com/input-output-hk/cardano-node
  image: inputoutput/cardano-node:latest
  imagePullPolicy: Always
  resources:
    limits:
      memory: 9Gi
      cpu: 2000m
  pvc: ""

dbSync:
  # https://github.com/input-output-hk/cardano-db-sync
  enabled: true
  image: inputoutput/cardano-db-sync:latest
  imagePullPolicy: Always
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
  pvc: ""

postgres:
  # Note: cardano-db-sync requires a Unix socket file for
  # postgres. Running cardano-node, db-sync, and postgres
  # on the same machine is the only supported paradigm. 
  enabled: true
  image: postgres:9.6.23
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: 1024Mi
      cpu: 1000m
  pvc: ""

socat:
  # If enabled, the node pod will run socat in a sidecar
  # container that will expose the cardano-node socket
  # over TCP. This permits cardano-cli to be used remotely.
  enabled: true
  imagePullPolicy: IfNotPresent
  image: alpine/socat:1.7.4.1-r2
  resources:
    limits:
      memory: 64Mi
      cpu: 50m
  port: 2100

